import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";

import { scanPath } from "../src/scanner.js";

function withTempDir(callback: (directory: string) => void): void {
  const directory = mkdtempSync(join(tmpdir(), "check-ai-slop-"));
  try {
    callback(directory);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

function hasGit(): boolean {
  try {
    execFileSync("git", ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function git(directory: string, args: string[]): void {
  execFileSync("git", ["-C", directory, ...args], { stdio: "ignore" });
}

test("detects the referenced was-gpt-here TypeScript helper", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "match.ts"),
      `function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });

    assert.equal(report.filesScanned, 1);
    assert.equal(report.confidence, "low");
    assert.ok(report.score >= 20);
    assert.ok((report.files[0]?.signalScores.authorship ?? 0) > 0);
    assert.equal(report.files[0]?.evidence[0]?.signalKind, "authorship");
    assert.equal(report.files[0]?.evidence[0]?.patternId, "ts_exact_is_record_guard");
  });
});

test("keeps small clean human code clean", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "math.ts"),
      `export function add(left: number, right: number): number {
  return left + right;
}
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });

    assert.equal(report.filesScanned, 1);
    assert.equal(report.score, 0);
    assert.equal(report.confidence, "clean");
    assert.deepEqual(report.files, []);
  });
});

test("scores clustered AI provenance, defensive code, and placeholder slop as high", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "generated.ts"),
      `// Created using GPT-5.5
// Replace with your actual endpoint URL

export function processUserDataResponse(input: unknown): string {
  /** This function processes user data.
   * Args: input data
   * Returns: processed data
   */
  if (input === null) throw new Error("The provided input cannot be empty");
  if (input === undefined) throw new Error("The provided input is not in a valid format");
  if (typeof input !== "object") throw new Error("The specified input is not in a valid format");
  return JSON.stringify(input);
}

export function handleUserDataResponse(value: unknown): string {
  if (value === null) return "";
  return processUserDataResponse(value);
}

export function validateUserDataInput(value: unknown): boolean {
  if (value === null) return false;
  if (value === undefined) return false;
  return true;
}

export function formatUserDataOutput(value: string): string {
  return value.trim();
}
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    const patternIds = new Set(report.files[0]?.evidence.map((item) => item.patternId));

    assert.equal(report.confidence, "high");
    assert.ok(report.score >= 70, `score was ${report.score}`);
    assert.ok(patternIds.has("self_admitted_ai_comment"));
    assert.ok(patternIds.has("template_customization_comment"));
    assert.ok(patternIds.has("null_guard_cluster"));
  });
});

test("reports hallucination-risk imports against package manifests", () => {
  withTempDir((directory) => {
    writeFileSync(join(directory, "package.json"), JSON.stringify({ dependencies: { react: "latest" } }));
    writeFileSync(
      join(directory, "widget.ts"),
      `import React from 'react';
import { makeWidget } from 'plausible-widget-utils';

export function Widget() {
  return makeWidget(React.createElement('div'));
}
`
    );

    const report = scanPath(directory);
    const patternIds = new Set(report.files.flatMap((file) => file.evidence.map((item) => item.patternId)));

    assert.ok(patternIds.has("unknown_dependency_reference"));
    assert.ok(patternIds.has("plausible_generic_package_name"));
  });
});

test("detects AI attribution markers from a real GitHub repository", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "cc_statistics_analyzer_excerpt.py"),
      `# Source: androidZzT/cc-statistics cc_stats/analyzer.py, _AI_COMMIT_MARKERS excerpt.
_AI_COMMIT_MARKERS = [
    "co-authored-by: claude",
    "co-authored-by: cursor",
    "co-authored-by: github copilot",
    "co-authored-by: codex",
    "co-authored-by: gemini",
    "generated by ai",
    "generated with claude",
    "generated by claude",
]
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    const patternIds = new Set(report.files[0]?.evidence.map((item) => item.patternId));

    assert.equal(report.confidence, "high");
    assert.ok(patternIds.has("ai_attribution_footer_cluster"));
    assert.ok(report.signalScores.authorship > report.signalScores.quality_risk);
    assert.ok(patternIds.has("self_admitted_ai_comment"));
  });
});

test("detects explicit AI provenance in recent Git commit metadata", { skip: !hasGit() }, () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "math.ts"),
      `export function add(left: number, right: number): number {
  return left + right;
}
`
    );
    git(directory, ["init"]);
    git(directory, ["config", "user.name", "Human Maintainer"]);
    git(directory, ["config", "user.email", "human@example.com"]);
    git(directory, ["add", "."]);
    git(directory, [
      "commit",
      "-m",
      "Add clean helper",
      "-m",
      "🤖 Generated with [Claude Code](https://claude.ai/code)\n\nCo-authored-by: Claude <noreply@anthropic.com>"
    ]);

    const report = scanPath(directory, { includeUnknownImports: false });
    const gitFile = report.files.find((file) => file.path === ".git/commit-history");
    const patternIds = new Set(gitFile?.evidence.map((item) => item.patternId));

    assert.equal(report.confidence, "high");
    assert.equal(gitFile?.confidence, "high");
    assert.ok(patternIds.has("git_ai_attribution_marker"));
    assert.ok((gitFile?.signalScores.authorship ?? 0) > 0);

    const disabledReport = scanPath(directory, { includeUnknownImports: false, includeGitSignals: false });
    assert.equal(disabledReport.files.some((file) => file.path === ".git/commit-history"), false);
  });
});

test("scopes Git signals to the scanned path and ignores non-AI generator links", { skip: !hasGit() }, () => {
  withTempDir((directory) => {
    git(directory, ["init"]);
    git(directory, ["config", "user.name", "Human Maintainer"]);
    git(directory, ["config", "user.email", "human@example.com"]);

    writeFileSync(join(directory, "clean.ts"), "export const clean = 1;\n");
    git(directory, ["add", "clean.ts"]);
    git(directory, ["commit", "-m", "Add clean file"]);

    writeFileSync(join(directory, "generated.ts"), "export const generated = 1;\n");
    git(directory, ["add", "generated.ts"]);
    git(directory, ["commit", "-m", "Add generated file", "-m", "Generated with [Claude Code](https://claude.ai/code)"]);

    writeFileSync(join(directory, "schema.ts"), "export const schema = 1;\n");
    git(directory, ["add", "schema.ts"]);
    git(directory, ["commit", "-m", "Regenerate schema", "-m", "Generated with [GraphQL Code Generator](https://the-guild.dev/graphql/codegen)"]);

    const directoryReport = scanPath(directory, { includeUnknownImports: false });
    assert.ok(directoryReport.files.some((file) => file.path === ".git/commit-history"));

    const cleanFileReport = scanPath(join(directory, "clean.ts"), { includeUnknownImports: false });
    assert.equal(cleanFileReport.confidence, "clean");
    assert.equal(cleanFileReport.files.some((file) => file.path === ".git/commit-history"), false);

    const nonAiGeneratorReport = scanPath(join(directory, "schema.ts"), { includeUnknownImports: false });
    assert.equal(nonAiGeneratorReport.confidence, "clean");
    assert.equal(nonAiGeneratorReport.files.some((file) => file.path === ".git/commit-history"), false);
  });
});

test("keeps a clean real GitHub repository snippet negative", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "is-plain-obj-index.js"),
      `export default function isPlainObject(value) {
\tif (typeof value !== 'object' || value === null) {
\t\treturn false;
\t}

\tconst prototype = Object.getPrototypeOf(value);
\treturn (prototype === null || prototype === Object.prototype || Object.getPrototypeOf(prototype) === null) && !(Symbol.toStringTag in value) && !(Symbol.iterator in value);
}
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });

    assert.equal(report.filesScanned, 1);
    assert.equal(report.confidence, "clean");
    assert.equal(report.score, 0);
    assert.deepEqual(report.files, []);
  });
});

test("detects unsafe PyYAML loading from Bandit real-repo examples", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "bandit_yaml_load_excerpt.py"),
      `import yaml
from yaml import CSafeLoader

def test_yaml_load():
    ystr = yaml.dump({'a': 1, 'b': 2, 'c': 3})
    y = yaml.load(ystr)
    yaml.dump(y)
    y = yaml.load(ystr, Loader=yaml.SafeLoader)

yaml.load("{}", Loader=yaml.Loader)
yaml.load("{}", CSafeLoader)
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    const yamlEvidence = report.files[0]?.evidence.filter((item) => item.patternId === "py_yaml_unsafe_load") ?? [];

    assert.ok(yamlEvidence.length >= 2);
    assert.ok(yamlEvidence.some((item) => item.excerpt.includes("yaml.load(ystr)")));
    assert.ok(yamlEvidence.some((item) => item.excerpt.includes("Loader=yaml.Loader")));
  });
});

test("detects expanded JavaScript security slop patterns", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "generated-route.ts"),
      `import fs from "node:fs";
import path from "node:path";

// @ts-ignore generated handler is loose
export function handler(req, res, app) {
  fs.readFileSync(path.join("/srv/uploads", req.params.name));
  const matcher = new RegExp(req.query.q);
  const profile = {};
  profile[req.body.field] = req.body.value;
  const sessionToken = Math.random().toString(36);
  app.use(session({ secret: "supersecret123", cookie: { secure: false, httpOnly: false } }));
  res.cookie("sid", sessionToken, { sameSite: "none" });
  res.redirect(req.query.next);
}
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    assert.equal(report.signalScores.authorship, 0);
    assert.ok(report.signalScores.quality_risk > 0);
    const patternIds = new Set(report.files[0]?.evidence.map((item) => item.patternId));

    for (const patternId of [
      "js_path_traversal_user_path",
      "js_regex_from_request_input",
      "js_dynamic_property_write_from_request",
      "insecure_random_token_generation",
      "hardcoded_session_secret_literal",
      "insecure_cookie_flags",
      "express_open_redirect_from_request",
      "lint_or_type_suppression_cluster"
    ]) {
      assert.ok(patternIds.has(patternId), `missing ${patternId}`);
    }
  });
});

test("detects expanded Python slop patterns from real vulnerable examples", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "vulnerable_flask_excerpt.py"),
      `import hashlib
import jinja2
import requests
import tempfile

app.config['SECRET_KEY_HMAC'] = 'secret'

def login(user, password, url):
    assert user.is_admin
    hash_pass = hashlib.md5(password).hexdigest()
    response = requests.get(url)
    temp_name = tempfile.mktemp()
    return hash_pass, response, temp_name

def collect(values=[]):
    return values

def render(templateLoader):
    return jinja2.Environment(autoescape=False, loader=templateLoader)

try:
    risky()
except:
    pass

items.push(1)
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    assert.equal(report.signalScores.authorship, 0);
    assert.ok(report.signalScores.quality_risk > 0);
    const patternIds = new Set(report.files[0]?.evidence.map((item) => item.patternId));

    for (const patternId of [
      "py_hardcoded_framework_secret",
      "py_assert_security_check",
      "weak_hash_for_security_context",
      "py_http_request_without_timeout",
      "py_tempfile_mktemp_race",
      "py_mutable_default_arg",
      "py_jinja_autoescape_disabled",
      "py_bare_except_swallow",
      "python_cross_language_contamination"
    ]) {
      assert.ok(patternIds.has(patternId), `missing ${patternId}`);
    }
  });
});

test("keeps mature Requests timeout API snippet negative for missing-timeout rule", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "requests_sessions_excerpt.py"),
      `def request(self, method, url, **kwargs):
    timeout = kwargs.pop("timeout", None)
    request = Request(method=method.upper(), url=url)
    prep = self.prepare_request(request)
    send_kwargs = {
        "timeout": timeout,
        "allow_redirects": kwargs.pop("allow_redirects", True),
    }
    return self.send(prep, **send_kwargs)
`
    );

    const report = scanPath(directory, { includeUnknownImports: false });
    const patternIds = new Set(report.files.flatMap((file) => file.evidence.map((item) => item.patternId)));

    assert.equal(patternIds.has("py_http_request_without_timeout"), false);
  });
});

test("CLI emits JSON and fail-on low exits with status 1", () => {
  withTempDir((directory) => {
    writeFileSync(
      join(directory, "match.ts"),
      `function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}
`
    );

    let output = "";
    assert.throws(
      () => {
        output = execFileSync(process.execPath, ["dist/cli.js", directory, "--json", "--no-unknown-imports", "--fail-on", "low"], {
          encoding: "utf8"
        });
      },
      (error: unknown) => {
        if (typeof error !== "object" || error === null || !("stdout" in error)) {
          return false;
        }
        output = String((error as { stdout: unknown }).stdout);
        return true;
      }
    );

    const payload = JSON.parse(output) as {
      confidence: string;
      signalScores: { authorship: number; quality_risk: number };
      files: Array<{ evidence: Array<{ patternId: string; signalKind: string }> }>;
    };
    assert.equal(payload.confidence, "low");
    assert.equal(payload.files[0]?.evidence[0]?.patternId, "ts_exact_is_record_guard");
    assert.equal(payload.files[0]?.evidence[0]?.signalKind, "authorship");
    assert.ok(typeof payload.signalScores.authorship === "number");
  });
});
