import type { PatternSpec } from "./types.js";

export const TS_JS: Record<string, true> = {
  ".ts": true,
  ".tsx": true,
  ".js": true,
  ".jsx": true,
  ".mjs": true,
  ".cjs": true,
  ".mts": true,
  ".cts": true
};
export const PYTHON: Record<string, true> = {
  ".py": true,
  ".pyi": true
};
export const TEST_EXTENSIONS: Record<string, true> = {
  ".py": true,
  ".js": true,
  ".jsx": true,
  ".ts": true,
  ".tsx": true
};

export const REGEX_PATTERNS: readonly PatternSpec[] = [
  {
    id: "ts_exact_is_record_guard",
    title: "Exact was-gpt-here TypeScript isRecord guard",
    category: "fingerprint",
    weight: 24,
    maxScore: 24,
    regex: /function\s+isRecord\s*\(\s*value\s*:\s*unknown\s*\)\s*:\s*value\s+is\s+Record\s*<\s*string\s*,\s*unknown\s*>\s*\{\s*return\s+typeof\s+value\s*={3}\s*['"]object['"]\s*&&\s*value\s*!==\s*null\s*;?\s*\}/gm,
    extensions: TS_JS,
    reason: "The referenced was-gpt-here project treats this normalized helper as a common GPT-style TypeScript artifact.",
    falsePositiveRisk: "A human can write or copy the same guard; strong only when it clusters with other signals.",
    source: "https://github.com/ericzakariasson/was-gpt-here"
  },
  {
    id: "ts_record_guard_family",
    title: "Generic unknown-to-Record type guard family",
    category: "defensive_typescript",
    weight: 9,
    maxScore: 18,
    regex: /\bfunction\s+(?:isRecord|isObject|isPlainObject)\s*\([^)]*:\s*unknown\s*\)\s*:\s*[^\{;\n]*\bis\s+Record\s*<\s*string\s*,\s*unknown\s*>/gm,
    extensions: TS_JS,
    reason: "Generalizes the exact GPT-style helper into the broader safe-object guard idiom often emitted around unknown JSON/API data.",
    falsePositiveRisk: "Common in validation-heavy TypeScript; low score unless repeated or paired with other evidence.",
    source: "https://github.com/ericzakariasson/was-gpt-here"
  },
  {
    id: "self_admitted_ai_comment",
    title: "Self-admitted AI-generation comment",
    category: "provenance",
    weight: 42,
    maxScore: 84,
    regex: /\b(?:generated|written|created|implemented|authored|coded)\s+(?:by|through|using|via|with)\s+(?:ChatGPT|OpenAI|Copilot|GPT[- ]?(?:3(?:\.5)?|4(?:o)?|5(?:\.5)?)|Claude(?:\s+Opus\s+4\.8)?|Anthropic|Gemini|Cursor|Windsurf)\b/gim,
    reason: "Self-admitted generated-code studies use this verb/preposition/model-family shape to collect GPT-written GitHub code.",
    falsePositiveRisk: "Can match docs or code that discusses AI; line context is reported so reviewers can reject those cases.",
    source: "https://arxiv.org/pdf/2406.19544"
  },
  {
    id: "ai_provenance_block",
    title: "AI provenance/model/prompt block in comments",
    category: "provenance",
    weight: 22,
    maxScore: 44,
    regex: /^\s*(?:(?:\/\/|#|\/\*|\*)\s*)?.*\b(?:prompt|model\s*:|generated on|human modifications|testing required|AI[- ]generated|LLM[- ]generated|Claude\s+Opus\s+4\.8|GPT[- ]?5\.5|Co-authored-by:\s*(?:Claude|ChatGPT|Cursor|Copilot))\b/gim,
    reason: "Self-admitted generated-code comments often preserve model, prompt, timestamp, human-edit, or testing metadata.",
    falsePositiveRisk: "AI product code and docs may mention these words; scan output keeps it as evidence, not proof.",
    source: "https://arxiv.org/pdf/2406.19544"
  },
  {
    id: "template_customization_comment",
    title: "Template/customization instruction left in source",
    category: "template_artifact",
    weight: 8,
    maxScore: 24,
    regex: /^\s*(?:\/\/|#|\*)\s*(?:TODO:?\s*)?(?:Replace|Customize|Add|Update|Insert|Configure)\b.*\b(?:your|actual|real|implementation|API key|endpoint|logic|path|URL|token)\b/gim,
    reason: "LLM sample code frequently leaves customization instructions that should not survive in production source.",
    falsePositiveRisk: "Scaffold/example repositories use similar comments intentionally.",
    source: "https://arxiv.org/pdf/2306.14397"
  },
  {
    id: "conversational_preamble",
    title: "Conversational assistant preamble left above code",
    category: "template_artifact",
    weight: 14,
    maxScore: 28,
    regex: /^(?:\s*(?:\/\/|#|\/\*)\s*)?(?:sure|certainly|of course|here(?:'|’)s|below is|the following|let me)\b.{0,120}$/gim,
    reason: "Heuristic detectors flag assistant-answer preambles accidentally pasted into source files.",
    falsePositiveRisk: "Docs, examples, and comment-heavy tutorials can contain conversational wording.",
    source: "https://github.com/Gabriel-Dalton/AI-Code-Detector"
  },
  {
    id: "tutorial_comment_phrasing",
    title: "Tutorial narration in comments",
    category: "comment_style",
    weight: 6,
    maxScore: 18,
    regex: /^\s*(?:\/\/|#|\*)\s*(?:First,?\s+we|Then,?\s+we|Now,?\s+we|Next,?\s+we|Let's)\b/gim,
    reason: "Public heuristic detectors and generated-code surveys call out tutorial phrasing as a recurring LLM artifact.",
    falsePositiveRisk: "Expected in educational material; weak by itself.",
    source: "https://github.com/BenjaminSRussell/Ai_code_detector"
  },
  {
    id: "this_function_prose",
    title: "Obvious 'This function/method/class...' prose",
    category: "comment_style",
    weight: 6,
    maxScore: 18,
    regex: /^\s*(?:\/\/|#|\*|\"\"\"|''')\s*(?:This\s+(?:function|method|class|module)|The\s+(?:function|method|class)\s+)\b/gim,
    reason: "Generated code often narrates the obvious API surface instead of project-specific intent.",
    falsePositiveRisk: "Normal in public APIs with explicit documentation standards.",
    source: "https://aquilax.ai/blog/detect-ai-written-code"
  },
  {
    id: "formal_error_sentence",
    title: "Over-formal generic error sentence",
    category: "error_handling",
    weight: 6,
    maxScore: 18,
    regex: /(?:raise\s+\w*Error\s*\(|throw\s+new\s+\w*Error\s*\(|logger\.(?:error|warning)\s*\(|console\.error\s*\().{0,140}['"](?:The\s+provided|The\s+specified|Invalid\s+[^'"]+provided|[^'"]+must\s+be\s+[^'"]+got\s+\{|[^'"]+is\s+not\s+in\s+a\s+valid\s+format|[^'"]+cannot\s+be\s+empty)/gis,
    reason: "AI code tends to produce polished, complete validation/error prose even in small helpers.",
    falsePositiveRisk: "Good SDKs and user-facing validation libraries also write polished errors.",
    source: "https://aquilax.ai/blog/detect-ai-written-code"
  },
  {
    id: "ts_catch_error_normalization",
    title: "Over-defensive TypeScript catch(error) normalization",
    category: "error_handling",
    weight: 7,
    maxScore: 21,
    regex: /catch\s*\(\s*(?:error|err)\s*\)\s*\{[\s\S]{0,500}\b(?:error|err)\s+instanceof\s+Error\s*\?\s*(?:error|err)\.message\s*:\s*(?:String\(\s*(?:error|err)\s*\)|['"][^'"]+['"])/gm,
    extensions: TS_JS,
    reason: "Generated TypeScript often normalizes unknown thrown values with a full defensive ternary before rethrowing/logging.",
    falsePositiveRisk: "Mature TypeScript projects deliberately do this at boundaries.",
    source: "https://arxiv.org/pdf/2311.02640"
  },
  {
    id: "console_error_fallback_catch",
    title: "catch + console.error + generic fallback",
    category: "error_handling",
    weight: 8,
    maxScore: 24,
    regex: /catch\s*\([^)]*\)\s*\{[\s\S]{0,300}console\.error\s*\([^)]*\)[\s\S]{0,300}\breturn\s+(?:\[\]|\{\}|null|false|true|undefined|['"][^'"]{0,8}['"]|default\w*)\s*;/gm,
    extensions: TS_JS,
    reason: "LLM code frequently wraps whole helpers in try/catch, logs to console, then returns a safe-looking default.",
    falsePositiveRisk: "Demos, CLIs, and UI fallbacks can use the same structure legitimately.",
    source: "https://arxiv.org/pdf/2306.14397"
  },
  {
    id: "python_catch_all_exception",
    title: "Catch-all Python exception with print/log/return",
    category: "error_handling",
    weight: 8,
    maxScore: 24,
    regex: /except\s+Exception\s+as\s+\w+\s*:\s*\n(?:[^\n]*\n){0,4}\s*(?:print|logger\.(?:error|exception)|return)\b/gm,
    extensions: PYTHON,
    reason: "Heuristic detectors call out broad `except Exception` plus generic handling as common AI-code structure.",
    falsePositiveRisk: "Boundary code can intentionally catch broad exceptions; weak without other signals.",
    source: "https://github.com/BenjaminSRussell/Ai_code_detector"
  },
  {
    id: "generic_error_copy",
    title: "Generic error-copy phrase",
    category: "error_handling",
    weight: 5,
    maxScore: 15,
    regex: /\b(?:an error occurred|something went wrong|failed to process|please try again later)\b/gim,
    reason: "Generated catch blocks often use generic, user-facing fallback copy instead of project-specific errors.",
    falsePositiveRisk: "Common UI copy; low-weight supporting evidence only.",
    source: "https://github.com/BenjaminSRussell/Ai_code_detector"
  },
  {
    id: "placeholder_secret_literal",
    title: "Placeholder secret or credential literal",
    category: "security_slop",
    weight: 16,
    maxScore: 48,
    regex: /\b(?:api[_-]?key|secret|token|password|private[_-]?key|jwt[_-]?secret)\s*=\s*['"](?:your[-_ ]?|change[-_ ]?me|replace[-_ ]?me|secret[_-]?key[_-]?here|<[^>]+>|x{3,}|test|demo|password)['"]/gim,
    reason: "LLM snippets often leave placeholder credentials that become production security slop.",
    falsePositiveRisk: "Examples and tests intentionally include dummy secrets; path context matters.",
    source: "https://aquilax.ai/blog/detect-ai-written-code"
  },
  {
    id: "weak_test_assertion",
    title: "Weak or tautological generated-test assertion",
    category: "test_slop",
    weight: 7,
    maxScore: 28,
    regex: /^\s*(?:assert\s+(?:result|response|data|output)\s*(?:is\s+not\s+None|!=\s*None)?|assert\s+True\b|self\.assertTrue\(\s*(?:result|response|data|output)\s*\)|expect\([^)]*\)\.(?:toBeTruthy|toBeDefined|toMatchSnapshot|not\.toThrow)\s*\()/gim,
    extensions: TEST_EXTENSIONS,
    reason: "Generated tests often assert that mocked or happy-path values merely exist, inflating coverage without behavior checks.",
    falsePositiveRisk: "Smoke tests may intentionally be weak; scan scores this only as supporting evidence.",
    source: "https://arxiv.org/html/2602.00409v1"
  },
  {
    id: "old_openai_node_sdk_in_modern_ts",
    title: "Outdated OpenAI Node SDK pattern",
    category: "stale_api",
    weight: 6,
    maxScore: 12,
    regex: /new\s+Configuration\s*\([\s\S]{0,220}\bapiKey\b[\s\S]{0,220}\)[\s\S]{0,220}new\s+OpenAIApi\s*\(/gm,
    extensions: TS_JS,
    reason: "Outdated-but-plausible API usage is a common LLM failure mode when code is generated from stale training examples.",
    falsePositiveRisk: "Old projects may legitimately still use old SDK versions; dependency versions should be checked in review.",
    source: "https://codeslick.dev/learn/ai-code-detection"
  },
  {
    id: "unsafe_dynamic_code_execution",
    title: "Unsafe dynamic code execution shortcut",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /\b(?:eval|exec|compile|Function)\s*\(/gm,
    reason: "LLM security research and standard security rules repeatedly flag generated shortcuts using dynamic code execution.",
    falsePositiveRisk: "Tooling/tests may intentionally evaluate code; higher severity when input is non-literal.",
    source: "https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html"
  },
  {
    id: "shell_command_interpolation",
    title: "Shell command interpolation shortcut",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /(?:subprocess\.(?:run|call|Popen|check_output|check_call)\([^\n)]*(?:shell\s*=\s*True|f['"]|\.format\(|\+\s*\w+)|child_process\.(?:exec|execSync)\s*\(\s*(?:`[^`]*\$\{|[^'"`\s]))/gms,
    reason: "Generated scripts often take shell=True/exec shortcuts that security tooling treats as command-injection risks.",
    falsePositiveRisk: "Build scripts with fixed commands can be safe; reviewers should check argument sources.",
    source: "https://github.com/eslint-community/eslint-plugin-security/blob/main/docs/avoid-command-injection-node.md"
  },
  {
    id: "tls_verification_disabled",
    title: "TLS certificate verification disabled",
    category: "security_slop",
    weight: 16,
    maxScore: 48,
    regex: /(?:requests\.[a-z]+\([^)]*verify\s*=\s*False|ssl\._create_unverified_context\s*\(|rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]0['"])/gims,
    reason: "AI snippets often include make-it-work TLS bypasses; this is concrete security slop, regardless of authorship.",
    falsePositiveRisk: "Local-dev self-signed fixtures can be legitimate; suppress only when clearly test-scoped.",
    source: "https://www.aikido.dev/blog/python-security-vulnerabilities"
  },
  {
    id: "placeholder_stub_implementation",
    title: "Placeholder or stub implementation shipped in code",
    category: "incomplete_code",
    weight: 10,
    maxScore: 30,
    regex: /\b(?:TODO|FIXME|XXX|HACK|placeholder|stub|not implemented|implement later|for now|temporary|mock implementation)\b[\s\S]{0,180}(?:pass\b|throw\s+new\s+Error\s*\(['"]Not implemented|return\s+(?:null|undefined|\{\}|\[\]|None)|\.\.\.)/gim,
    reason: "AI-generated code often looks complete while leaving plausible placeholder surfaces behind.",
    falsePositiveRisk: "Normal backlog comments in tests/examples can match; stronger in exported or API code.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector"
  },
  {
    id: "js_any_escape_hatch",
    title: "TypeScript any escape hatch cluster",
    category: "type_safety_slop",
    weight: 4,
    maxScore: 16,
    regex: /\b(?:as\s+any|:\s*any\b|<any>)/g,
    extensions: TS_JS,
    reason: "AI slop detectors treat repeated `any` escape hatches as quality risk, especially when paired with generated-looking defensive wrappers.",
    falsePositiveRisk: "Migration code and untyped third-party boundaries may require `any`; low-weight supporting evidence only.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector"
  },
  {
    id: "disabled_test_artifact",
    title: "Disabled generated-test artifact",
    category: "test_slop",
    weight: 8,
    maxScore: 24,
    regex: /\b(?:describe|it|test)\.(?:skip|todo|only)\s*\(|\b(?:xit|xtest)\s*\(/g,
    extensions: TEST_EXTENSIONS,
    reason: "Structural slop detectors flag disabled tests because generated suites often leave brittle scenarios skipped instead of fixed.",
    falsePositiveRisk: "Intentional quarantines exist; report as review priority, not proof.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector"
  },
  {
    id: "ai_attribution_footer_cluster",
    title: "Cluster of AI attribution footer strings",
    category: "provenance",
    weight: 10,
    maxScore: 50,
    regex: /\b(?:(?:generated|created|written|authored|coded)\s+(?:by|with|using|via)\s+(?:AI|Claude|Anthropic|GPT|ChatGPT|Copilot|Cursor|Codex|Gemini|OpenAI)|Co-authored-by:?\s*(?:AI|Claude|Anthropic|ChatGPT|Copilot|Cursor|Codex|Gemini|OpenAI)|AI[-_. ]?(?:assisted|generated))\b/gim,
    reason: "Real repositories that block or measure AI code often keep arrays of generated-by/co-authored-by/AI-assisted footer markers; clusters are a strong provenance-review signal.",
    falsePositiveRisk: "Detector, policy-hook, and analytics repositories intentionally contain these strings; review path and intent before treating it as authored code.",
    source: "https://raw.githubusercontent.com/androidZzT/cc-statistics/main/cc_stats/analyzer.py"
  },
  {
    id: "py_yaml_unsafe_load",
    title: "Unsafe PyYAML load",
    category: "security_slop",
    weight: 14,
    maxScore: 42,
    regex: /\byaml\.load\s*\((?![^)\n]*(?:Loader\s*=\s*yaml\.(?:SafeLoader|CSafeLoader)|,\s*(?:yaml\.)?(?:SafeLoader|CSafeLoader)))[^)\n]*\)|Loader\s*=\s*yaml\.(?:Loader|UnsafeLoader)/gm,
    extensions: PYTHON,
    reason: "Bandit flags yaml.load without a safe loader because it can instantiate arbitrary Python objects; generated snippets often choose convenience deserialization APIs.",
    falsePositiveRisk: "Trusted legacy config loaders may intentionally use object YAML; reviewers need data-source context.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b506_yaml_load.html"
  },
  {
    id: "js_sql_query_interpolation",
    title: "JavaScript SQL query string interpolation",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /\b(?:query|execute|raw)\s*\(\s*(?:`[^`]*(?:SELECT|INSERT|UPDATE|DELETE)[^`]*\$\{|['"][^'"]*(?:SELECT|INSERT|UPDATE|DELETE)[^'"]*['"]\s*\+)/gim,
    extensions: TS_JS,
    reason: "CodeQL documents string-built SQL queries as injection risks; AI-generated backend examples often skip parameterization.",
    falsePositiveRisk: "Escaped values, trusted migration scripts, or safe query wrappers can look similar to a regex scanner.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-sql-injection/"
  },
  {
    id: "py_sql_query_interpolation",
    title: "Python SQL query string interpolation",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /(?:cursor|conn|db)\.(?:execute|executemany)\s*\(\s*(?:f['"][^'"]*(?:SELECT|INSERT|UPDATE|DELETE)|['"][^'"]*(?:SELECT|INSERT|UPDATE|DELETE)[^'"]*['"]\s*(?:%|\.format\(|\+))/gim,
    extensions: PYTHON,
    reason: "CodeQL's Python SQL-injection guidance flags f-string/format/concatenated queries; generated data-access snippets commonly use these shortcuts.",
    falsePositiveRisk: "Static migration SQL and trusted internal scripts may compose SQL safely outside request paths.",
    source: "https://codeql.github.com/codeql-query-help/python/py-sql-injection/"
  },
  {
    id: "express_cors_wildcard_credentials",
    title: "Permissive CORS wildcard with credentials",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /cors\s*\(\s*\{[\s\S]{0,220}origin\s*:\s*['"]\*['"][\s\S]{0,220}credentials\s*:\s*true|Access-Control-Allow-Origin[^;\n]*\*[\s\S]{0,180}Access-Control-Allow-Credentials[^;\n]*true/gim,
    extensions: TS_JS,
    reason: "LLM-scaffolded web apps often broaden CORS to make requests work, creating an access-control review risk.",
    falsePositiveRisk: "Internal/dev APIs and browser-rejected configurations can match; check deployment scope.",
    source: "https://www.endorlabs.com/learn/the-most-common-security-vulnerabilities-in-ai-generated-code"
  },
  {
    id: "express_direct_html_response_xss",
    title: "Direct HTML response concatenation",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /res\.(?:send|write|end)\s*\(\s*(?:`[^`]*<[^>]+>[^`]*\$\{|['"][^'"]*<[^>]+>[^'"]*['"]\s*\+|\w+\s*\+)/gim,
    extensions: TS_JS,
    reason: "Semgrep's Express XSS guidance flags raw HTML concatenation in responses; generated demos often bypass escaping/templates.",
    falsePositiveRisk: "Static literal pages and already-sanitized CMS/admin rendering need human review.",
    source: "https://docs.semgrep.dev/cheat-sheets/express-xss/"
  },
  {
    id: "template_unescaped_interpolation",
    title: "Unescaped template interpolation",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /<%-[\s\S]{0,120}%>|\{\{\{[\s\S]{0,120}\}\}\}|\{\{\s*&|!\{[^}]+\}|^\s*\w+\([^)]*!=/gm,
    reason: "Template engines expose raw-output syntax that generated snippets may use without sanitizer context.",
    falsePositiveRisk: "Legitimate rich-text rendering can be safe when paired with sanitizer enforcement.",
    source: "https://docs.semgrep.dev/cheat-sheets/express-xss/"
  },
  {
    id: "python_flask_debug_true",
    title: "Flask debug mode enabled",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /app\.run\s*\([^)]*debug\s*=\s*True|app\.debug\s*=\s*True|FLASK_DEBUG\s*=\s*['"]?1/gm,
    extensions: PYTHON,
    reason: "Bandit flags Flask debug mode because generated demos often ship development settings into app code.",
    falsePositiveRisk: "Local examples and tests can intentionally set debug mode; production path context matters.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b201_flask_debug_true.html"
  },
  {
    id: "jwt_verification_disabled",
    title: "JWT verification bypass option",
    category: "security_slop",
    weight: 14,
    maxScore: 42,
    regex: /jwt\.decode\s*\([^)]*(?:verify\s*=\s*False|verify_signature['"]?\s*:\s*False)|jwt\.verify\s*\([^)]*\{[^}]*ignoreExpiration\s*:\s*true|\bdecode\s*\([^)]*\{[^}]*complete\s*:\s*true/gim,
    reason: "AI auth scaffolds may disable signature/expiration checks to make examples work; auth bypasses deserve explicit review.",
    falsePositiveRisk: "Token-inspection utilities may decode without trust decisions; check whether the result gates access.",
    source: "https://www.endorlabs.com/learn/the-most-common-security-vulnerabilities-in-ai-generated-code"
  },
  {
    id: "python_pickle_deserialization",
    title: "Python pickle/dill deserialization",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /\b(?:pickle|cPickle|dill)\.(?:load|loads)\s*\(/gm,
    extensions: PYTHON,
    reason: "Pickle-style deserialization is unsafe for untrusted data and is a recurring convenience shortcut in generated Python helpers.",
    falsePositiveRisk: "Trusted local model/cache loading is common; higher concern when input names imply request/body/file/user data.",
    source: "https://docs.python.org/3/library/pickle.html"
  },
  {
    id: "js_path_traversal_user_path",
    title: "Request-controlled file path",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /(?:fs\.(?:readFile|readFileSync|writeFile|writeFileSync|createReadStream|unlink|rm)|res\.sendFile)\s*\([^;\n]*(?:req\.(?:query|params|body)|path\.(?:join|resolve)\s*\([^)]*req\.(?:query|params|body))/gim,
    extensions: TS_JS,
    reason: "CodeQL flags request-controlled paths in file APIs; generated Express/file-serving snippets often join req.params directly into filesystem paths.",
    falsePositiveRisk: "Safe code may normalize and validate path containment before this call; regex cannot prove nearby guards.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-path-injection/"
  },
  {
    id: "py_path_traversal_user_path",
    title: "User-controlled Python file path",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /\b(?:open|send_file)\s*\([^;\n]*(?:request\.(?:args|form|json|files)|input\s*\(|sys\.argv)|\b(?:Path|os\.path\.(?:join|abspath))\s*\([^;\n]*(?:request\.(?:args|form|json|files)|input\s*\(|sys\.argv)/gim,
    extensions: PYTHON,
    reason: "Generated Flask/CLI helpers often accept filenames directly from request or argv data, creating path traversal review risk.",
    falsePositiveRisk: "Internal tools may trust argv, and validation may happen before the flagged call.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-path-injection/"
  },
  {
    id: "js_regex_from_request_input",
    title: "RegExp built from request input",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /new\s+RegExp\s*\([^;\n]*(?:req\.(?:query|params|body)|location\.(?:search|hash)|URLSearchParams)/gim,
    extensions: TS_JS,
    reason: "CodeQL flags regex injection/ReDoS risk when user input becomes a regular expression; generated search handlers often do this directly.",
    falsePositiveRisk: "Safe if input is escaped first with a proven escapeRegExp helper.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-regex-injection/"
  },
  {
    id: "js_dynamic_property_write_from_request",
    title: "Dynamic property write from request input",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /\w+\s*\[\s*req\.(?:query|params|body)\.[\w$]+\s*\]\s*=|Object\.assign\s*\([^;\n]*req\.body/gim,
    extensions: TS_JS,
    reason: "CodeQL documents remote property injection when request-controlled keys are written into objects; generated PATCH/update handlers often trust field names.",
    falsePositiveRisk: "Safe when writing to a Map/null-prototype object or after explicit allow-list checks.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-remote-property-injection/"
  },
  {
    id: "py_assert_security_check",
    title: "Python assert used for security-sensitive check",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /^\s*assert\s+[^\n]*(?:user|auth|token|permission|role|admin|owner|password|secret|csrf|signature|is_authenticated)\b/gim,
    extensions: PYTHON,
    reason: "Bandit flags assert usage because optimized Python removes assertions; generated auth guards sometimes use assert as validation.",
    falsePositiveRisk: "Tests and internal invariants may intentionally assert; check path and whether the assertion gates security.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html"
  },
  {
    id: "py_http_request_without_timeout",
    title: "Python HTTP request without timeout",
    category: "reliability_slop",
    weight: 8,
    maxScore: 24,
    regex: /\b(?:requests|httpx)\.(?:get|post|put|patch|delete|head|options|request)\s*\((?![^\n)]*timeout\s*=)[^\n)]*\)|\b(?:requests|httpx)\.(?:get|post|put|patch|delete|head|options|request)\s*\([^\n)]*timeout\s*=\s*None/gim,
    extensions: PYTHON,
    reason: "Bandit flags requests/httpx calls without timeouts because generated API clients often hang indefinitely under network failure.",
    falsePositiveRisk: "Wrapper sessions may enforce defaults elsewhere; still worth reviewing at boundaries.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b113_request_without_timeout.html"
  },
  {
    id: "weak_hash_for_security_context",
    title: "Weak hash in security-sensitive context",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /(?:hashlib\.(?:md5|sha1)\s*\([^;\n]*(?:password|token|secret|signature|auth|session|csrf)|hashlib\.new\s*\(\s*(?:name\s*=\s*)?['"](?:md4|md5|sha1|sha)['"][^;\n]*(?:password|token|secret|signature|auth|session|csrf)|crypto\.createHash\s*\(\s*['"](?:md4|md5|sha1)['"]\s*\)[\s\S]{0,120}\b(?:password|token|secret|signature|auth|session|csrf))/gim,
    reason: "Bandit/CodeQL flag MD5/SHA1 in security contexts; generated auth examples often pick familiar weak hashes.",
    falsePositiveRisk: "Non-security checksums, ETags, and legacy compatibility can legitimately use weak hashes.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b324_hashlib.html"
  },
  {
    id: "insecure_random_token_generation",
    title: "Non-cryptographic random token generation",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /\b(?:token|secret|password|passwd|session|csrf|nonce|otp|api[_-]?key)\w*\s*=\s*(?:Math\.random\s*\(|random\.(?:random|randint|choice)\s*\()|(?:Math\.random\s*\(|random\.(?:random|randint|choice)\s*\()[\s\S]{0,120}\b(?:token|secret|password|passwd|session|csrf|nonce|otp|api[_-]?key)\b/gim,
    reason: "Security guidance requires CSPRNGs for secrets; generated auth snippets often use Math.random or Python random for tokens.",
    falsePositiveRisk: "Demo IDs, test fixtures, and non-security correlation IDs may not need CSPRNGs.",
    source: "https://codeql.github.com/codeql-query-help/javascript/js-insecure-randomness/"
  },
  {
    id: "hardcoded_session_secret_literal",
    title: "Hardcoded session/JWT secret literal",
    category: "security_slop",
    weight: 14,
    maxScore: 42,
    regex: /(?:session|cookieSession)\s*\(\s*\{[\s\S]{0,220}\b(?:secret|keys?)\s*:\s*(?:['"][^'"\${}]{8,}['"]|\[\s*['"][^'"\${}]{8,}['"])|jwt\.(?:sign|verify)\s*\([^,\n]+,\s*['"][^'"\${}]{8,}['"]/gim,
    extensions: TS_JS,
    reason: "Express security guidance expects secrets outside source; generated session/JWT scaffolds often hardcode plausible-looking literals rather than placeholders.",
    falsePositiveRisk: "Tests/examples can use fixed secrets intentionally; avoid treating fixture code as production.",
    source: "https://expressjs.com/en/advanced/best-practice-security/"
  },
  {
    id: "express_open_redirect_from_request",
    title: "Express redirect from request parameter",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /res\.redirect\s*\(\s*(?:req\.(?:query|params|body)\.[\w$]+|new\s+URL\s*\([^)]*req\.(?:query|params|body))/gim,
    extensions: TS_JS,
    reason: "Express security docs warn to validate redirect targets; generated login/logout handlers often redirect to request-controlled next URLs.",
    falsePositiveRisk: "Safe if target was allow-listed before redirect; regex cannot see all validators.",
    source: "https://expressjs.com/en/advanced/best-practice-security/"
  },
  {
    id: "insecure_cookie_flags",
    title: "Insecure auth cookie flags",
    category: "security_slop",
    weight: 10,
    maxScore: 30,
    regex: /(?:res\.cookie|session|cookieSession)\s*\([\s\S]{0,260}(?:httpOnly\s*:\s*false|secure\s*:\s*false|sameSite\s*:\s*['"]none['"][\s\S]{0,80}(?!secure\s*:\s*true))/gim,
    extensions: TS_JS,
    reason: "Generated auth/session examples often disable cookie protections to make local development work.",
    falsePositiveRisk: "Development-only code may intentionally disable secure cookies; deployment context matters.",
    source: "https://expressjs.com/en/advanced/best-practice-security/"
  },
  {
    id: "py_tempfile_mktemp_race",
    title: "Race-prone tempfile.mktemp usage",
    category: "security_slop",
    weight: 8,
    maxScore: 24,
    regex: /\btempfile\.mktemp\s*\(/gm,
    extensions: PYTHON,
    reason: "Ruff and Bandit-style checks flag tempfile.mktemp because generated scripts may choose the obvious but race-prone API.",
    falsePositiveRisk: "Rare legacy code may accept the race; most uses should move to NamedTemporaryFile or mkstemp.",
    source: "https://docs.astral.sh/ruff/rules/suspicious-mktemp-usage/"
  },
  {
    id: "py_bare_except_swallow",
    title: "Bare except that swallows control flow",
    category: "error_handling",
    weight: 10,
    maxScore: 30,
    regex: /^\s*except\s*:\s*\n(?:[^\n]*\n){0,2}\s*(?:pass|return\b|continue\b|break\b)/gm,
    extensions: PYTHON,
    reason: "Bare except/pass appears in detector fixtures and hides all failures; generated code often suppresses errors instead of handling typed exceptions.",
    falsePositiveRisk: "Top-level cleanup loops sometimes intentionally swallow all errors, but should be documented narrowly.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html"
  },
  {
    id: "py_hardcoded_framework_secret",
    title: "Hardcoded framework secret config",
    category: "security_slop",
    weight: 14,
    maxScore: 42,
    regex: /(?:app\.config\s*\[\s*['"][A-Z0-9_]*(?:SECRET|PASSWORD|TOKEN|KEY)[A-Z0-9_]*['"]\s*\]|app\.secret_key)\s*=\s*['"][^'"]{3,}['"]/gm,
    extensions: PYTHON,
    reason: "Bandit hardcoded-password rules catch literal framework secrets that generated Flask examples often leave in app code.",
    falsePositiveRisk: "Intentionally vulnerable training apps and local examples can contain fixed secrets.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b105_hardcoded_password_string.html"
  },
  {
    id: "py_jinja_autoescape_disabled",
    title: "Jinja2 autoescape disabled",
    category: "security_slop",
    weight: 12,
    maxScore: 36,
    regex: /\b(?:jinja2\.)?Environment\s*\([\s\S]{0,220}\bautoescape\s*=\s*False/gm,
    extensions: PYTHON,
    reason: "Bandit flags Jinja2 autoescape=False because generated templating examples may bypass escaping globally.",
    falsePositiveRisk: "Non-HTML templates or sanitized trusted input can legitimately disable autoescape.",
    source: "https://bandit.readthedocs.io/en/latest/plugins/b701_jinja2_autoescape_false.html"
  },
  {
    id: "py_mutable_default_arg",
    title: "Python mutable default argument",
    category: "correctness_slop",
    weight: 8,
    maxScore: 24,
    regex: /^\s*def\s+\w+\s*\([^\n)]*=\s*(?:\[\]|\{\}|set\(\)|dict\(\)|list\(\))/gm,
    extensions: PYTHON,
    reason: "AI slop detectors list mutable Python defaults as a concrete generated-code correctness bug.",
    falsePositiveRisk: "Rare intentional shared caches use mutable defaults; most matches are defects.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector/blob/main/docs/PATTERNS.md"
  },
  {
    id: "python_cross_language_contamination",
    title: "Cross-language idiom in Python file",
    category: "correctness_slop",
    weight: 8,
    maxScore: 24,
    regex: /\.(?:push|equals|toString|each)\s*\(|\.length\b|\.each\s*\{/g,
    extensions: PYTHON,
    reason: "AI slop detectors call out cross-language contamination where LLMs emit JavaScript/Java/Ruby idioms inside Python.",
    falsePositiveRisk: "Python wrappers around JS objects or documentation strings can mention these idioms.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector/blob/main/docs/PATTERNS.md"
  },
  {
    id: "lint_or_type_suppression_cluster",
    title: "Lint/type suppression comment",
    category: "maintenance_slop",
    weight: 5,
    maxScore: 20,
    regex: /\b(?:eslint-disable(?:-next-line)?|ts-ignore|ts-expect-error|type:\s*ignore|noqa(?::\s*\w+)?|pylint:\s*disable=|istanbul\s+ignore|c8\s+ignore)\b/g,
    reason: "Generated fixes often silence type/lint/coverage tooling instead of repairing the underlying code.",
    falsePositiveRisk: "Legacy migrations and generated clients can need targeted suppressions; treat as supporting evidence.",
    source: "https://github.com/flamehaven01/AI-SLOP-Detector/blob/main/docs/PATTERNS.md"
  }
];
